[theme]
primaryColor="#2E7D32"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#F5F5F5"
textColor="#1A1A1A"
font="sans serif"

[server]
maxUploadSize = 200
enableXsrfProtection = true
enableCORS = false

[client]
showSidebarNavigation = false
